/lidar_scan_matcher_node:
  ros__parameters:
    base_frame_id: "base_link"
    registration_method: "NDT_OMP"
    displacement: 1.0
    max_scan_accumulate_num: 20

    # Common Settings for Scan Matching
    max_iteration: 64
    omp_num_thread: 4
    transformation_epsilon: 0.01

    # NDT_OMP
    step_size: 0.1
    ndt_resolution: 2.0

    # FAST_GICP
    max_correspondence_distance: 2.0
    correspondence_randomness: 20
