/graph_based_slam_node:
  ros__parameters:
    rate: 3.0
    search_key_frame_num: 3
    search_radius: 50.0
    score_threshold: 2.5
    search_for_candidate_threshold: 15.0
    accumulate_distance_threshold: 25.0
    registration_method: "FAST_GICP"

    # Common Settings for Scan Matching
    max_iteration: 64
    omp_num_thread: 4
    #transformation_epsilon: 0.01 # NDT_OMP
    transformation_epsilon: 0.01 # GICP

    # NDT_OMP
    step_size: 0.1
    ndt_resolution: 1.5

    # FAST_GICP
    max_correspondence_distance: 2.0
    correspondence_randomness: 20
    max_optimizer_iteration: 20

    # GICP
    correspondence_distance: 2.0
    euclidean_fitness_epsilon: 1e-08
    ransac_iteration: 0